jobs:
      build:
        docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run: gradle test
          - store_test_results:
                path: test-results
      test:          
         docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run: gradle jar
          - store_artifacts:
                path: /code/test-results
                destination: prefix
workflows:
    version: 2.0
    build_and_test:
    jobs:
      - build
      - test
    
   
           
