workflows:
    version: 2.0
    jobs:
      build:
        docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run: 
              name: build and test
              command: gradle test
          - store_test_results:
                path: build/test-results
      package:          
         docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - checkout
          - run:
             name: package
             command: gradle jar
          - store_artifacts:
                name: publish jar
                path: /code/test-results
                destination: prefix
   
           
